"use client";
import{useEffect,useMemo,useState}from"react";
import{dfSupabase}from"../../../lib/df-browser";
import{DFSubHeader,DFBottomNav,DFLiveNotice,DFLiveAd}from"../../../components/df-shell";

const regionMap={"서울특별시":"서울","부산광역시":"부산","대구광역시":"대구","인천광역시":"인천","광주광역시":"광주","대전광역시":"대전","울산광역시":"울산","세종특별자치시":"세종","경기도":"경기","강원특별자치도":"강원","강원도":"강원","충청북도":"충북","충청남도":"충남","전북특별자치도":"전북","전라북도":"전북","전라남도":"전남","경상북도":"경북","경상남도":"경남","제주특별자치도":"제주"};
function regionOf(address){const first=(address||"").split(" ")[0];return regionMap[first]||first.replace(/(특별시|광역시|특별자치시|특별자치도|도)$/,"")}
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString("ko-KR",{maximumFractionDigits:1}):"확인 필요";
const won=n=>Number.isFinite(Number(n))?Number(n).toLocaleString("ko-KR")+"원":"확인 필요";
const money=n=>{n=Number(n);if(!Number.isFinite(n))return"확인 필요";return n>=1e8?(n/1e8).toLocaleString("ko-KR",{maximumFractionDigits:2})+"억원":Math.round(n/1e4).toLocaleString("ko-KR")+"만원"};
function ringOf(g){if(!g?.coordinates)return null;if(g.type==="Polygon")return g.coordinates[0]||null;if(g.type==="MultiPolygon"){let best=null;for(const p of g.coordinates){const r=p?.[0];if(r&&(!best||r.length>best.length))best=r}return best}return null}
function ParcelShape({geometry,label,pnu}){
 const points=useMemo(()=>{const ring=ringOf(geometry);if(!ring||ring.length<3)return null;const xs=ring.map(x=>Number(x[0])),ys=ring.map(x=>Number(x[1]));let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const dx=Math.max(maxX-minX,1e-8),dy=Math.max(maxY-minY,1e-8),pad=.12;minX-=dx*pad;maxX+=dx*pad;minY-=dy*pad;maxY+=dy*pad;return ring.map(([x,y])=>(((x-minX)/(maxX-minX)*1000).toFixed(1))+","+(((maxY-y)/(maxY-minY)*700).toFixed(1))).join(" ")},[geometry]);
 if(!points)return <div className="dfParcelEmpty">필지 경계 데이터가 반환되지 않았습니다.</div>;
 return <div className="dfParcelMap"><svg viewBox="0 0 1000 700" preserveAspectRatio="xMidYMid meet"><rect width="1000" height="700" fill="#f3f5f7"/><polygon points={points} fill="rgba(201,231,145,.68)" stroke="#f47721" strokeWidth="8" vectorEffect="non-scaling-stroke"/><text x="500" y="350" textAnchor="middle" dominantBaseline="middle" fill="#9a3e0c" fontSize="52" fontWeight="900">{label||"선택 필지"}</text><text x="28" y="664" fill="#687789" fontSize="23">VWorld 연속지적도 · PNU {pnu||""}</text></svg></div>
}
async function getJson(url){try{const r=await fetch(url,{cache:"no-store"});const j=await r.json();return{...j,_status:r.status}}catch(e){return{ok:false,error:"NETWORK_ERROR",detail:e.message}}}
export default function LandAnalysis(){
 const[address,setAddress]=useState(""),[region,setRegion]=useState(""),[base,setBase]=useState(null),[tx,setTx]=useState(null),[reg,setReg]=useState(null),[env,setEnv]=useState(null),[road,setRoad]=useState(null),[loading,setLoading]=useState(true),[user,setUser]=useState(null),[existing,setExisting]=useState(null),[news,setNews]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{let live=true;(async()=>{const addr=new URLSearchParams(window.location.search).get("address")||"";const rg=regionOf(addr);setAddress(addr);setRegion(rg);const{data:{user:u}}=await dfSupabase.auth.getUser();if(!live)return;setUser(u||null);if(u&&addr){const{data:w}=await dfSupabase.from("df_land_watchlists").select("*").eq("profile_id",u.id).eq("address_text",addr).maybeSingle();if(live)setExisting(w||null)}if(rg){const{data:a}=await dfSupabase.from("df_articles").select("id,title,category,published_at").in("status",["published","corrected"]).eq("region_code",rg).order("published_at",{ascending:false}).limit(5);if(live)setNews(a||[])}if(!addr){setLoading(false);return}const b=await getJson("/api/land?address="+encodeURIComponent(addr));if(!live){return}setBase(b);if(b?.ok){const q=new URLSearchParams({pnu:String(b.pnu||""),lon:String(b.point?.lon||""),lat:String(b.point?.lat||"")});const [t,r,e,rd]=await Promise.all([getJson("/api/land-transactions?pnu="+encodeURIComponent(b.pnu||"")+"&months=12"),getJson("/api/land-regulation?"+q),getJson("/api/building-envelope?address="+encodeURIComponent(addr)),getJson("/api/road-access?"+q)]);if(live){setTx(t);setReg(r);setEnv(e);setRoad(rd)}}setLoading(false)})();return()=>{live=false}},[]);
 async function save(){if(!address)return;if(!user){location.href="/login?next="+encodeURIComponent(location.pathname+location.search);return}setBusy(true);setMsg("");try{const{data,error}=await dfSupabase.from("df_land_watchlists").insert({profile_id:user.id,label:address,address_text:address,parcel_key:base?.pnu||address,region_code:region||null,radius_m:1000,is_active:true}).select().single();if(error)throw error;location.href="/asset/"+data.id}catch(e){setMsg(e.code==="23505"?"이미 등록한 부동산입니다.":e.message)}finally{setBusy(false)}}
 const land=base?.official?.land||{},parcel=base?.official?.parcel||{},zones=reg?.zoning?.zones||base?.official?.zoning?.zones||[],districts=reg?.zoning?.districts||base?.official?.zoning?.districts||[],areas=reg?.zoning?.areas||base?.official?.zoning?.areas||[];
 const transactions=(tx?.transactions||[]).filter(x=>!x.cancelled&&Number.isFinite(Number(x.pricePerPyeong))).slice(0,8);const avg=transactions.length?Math.round(transactions.reduce((s,x)=>s+Number(x.pricePerPyeong),0)/transactions.length):null;
 const decision=env?.decision||{},scale=env?.scale||{},confirmed=decision.status==="confirmed";
 return <main className="focusShell dfHigh"><DFSubHeader title="땅짚고" kicker="LAND INTELLIGENCE" back="/search" right={null}/><DFLiveNotice placement="land" region={region||null}/>
 <section className="dfLandResultHero"><small>JITGO LAND ENGINE</small><h1>{address||"분석할 부동산을 선택하세요."}</h1><p>짓고에서 검증한 토지 엔진을 연결해 공식 필지·실거래·규제·건축규모·접도를 순서대로 확인합니다.</p></section>
 {base?.ok&&<section className="dfLandSummary"><div><small>지목</small><b>{land.type||"확인 필요"}</b></div><div><small>면적</small><b>{fmt(land.area)}㎡</b></div><div><small>용도지역</small><b>{zones[0]||"확인 필요"}</b></div><div className={confirmed?"ok":"warn"}><small>건축규모</small><b>{confirmed?"기본검토 가능":"추가확인 필요"}</b></div></section>}
 {base?.ok&&<div className="dfLandLegend"><span><i className="ok"></i>공식 확인/기본검토 가능</span><span><i className="warn"></i>추가 확인 필요</span></div>}
 {loading?<section className="dfLandAnalysisCard"><h2>토지 분석 중</h2><div className="dfLandLoading"><span></span><span></span><span></span></div></section>:!base?.ok?<section className="dfLandAnalysisCard"><h2>공식 토지정보 조회</h2><div className="dfLandWarn"><b>조회하지 못했습니다.</b><span>{base?.detail||base?.error||"주소 또는 공식 API 연결을 확인하세요."}</span></div></section>:<>
 <section className="dfLandAnalysisCard"><div className="dfLandCardHead"><div><small>01 · OFFICIAL PARCEL</small><h2>토지 선택 & 공식 토지정보</h2></div><span className="ok">공식조회</span></div><div className="dfLandMetrics"><div><span>PNU</span><b>{base.pnu||"확인 필요"}</b></div><div><span>지번</span><b>{parcel.properties?.jibun||"확인 필요"}</b></div><div><span>지목</span><b>{land.type||"확인 필요"}</b></div><div><span>면적</span><b>{fmt(land.area)}㎡</b></div></div><a className="dfLandOfficialBtn" href="https://www.kgeop.go.kr/info/infoMap.do?initMode=L" target="_blank" rel="noreferrer">K-GeoP 토지정보 바로보기 ↗</a></section>
 <section className="dfLandAnalysisCard"><div className="dfLandCardHead"><div><small>02 · CADASTRAL</small><h2>지적도·필지</h2></div><span>VWorld</span></div><ParcelShape geometry={parcel.geometry} label={parcel.properties?.jibun} pnu={base.pnu}/><p className="dfLandSource">출처: 국토교통부 VWorld 연속지적도</p></section>
 <section className="dfLandAnalysisCard"><div className="dfLandCardHead"><div><small>03 · LAND VALUE</small><h2>토지 기본정보</h2></div><span>공식자료</span></div><div className="dfLandMetrics"><div><span>면적</span><b>{fmt(land.area)}㎡</b><em>약 {fmt(Number(land.area)/3.305785)}평</em></div><div><span>공시지가</span><b>{won(land.price)} /㎡</b><em>{land.priceYear?land.priceYear+"년 기준":""}</em></div><div className="wide"><span>전체 공시지가 환산</span><b>{money(Number(land.area)*Number(land.price))}</b><em>시세·감정가가 아닌 공식 공시지가 단순 환산</em></div></div></section>
 <section className="dfLandAnalysisCard"><div className="dfLandCardHead"><div><small>04 · TRANSACTIONS</small><h2>주변 실거래</h2></div><span className={tx?.ok?"ok":"warn"}>{tx?.ok?"국토부 공식":"확인 필요"}</span></div>{transactions.length?<><div className="dfTxSummary"><div><span>비교거래</span><b>{transactions.length}건</b></div><div><span>평균 평당가</span><b>{money(avg)}</b></div></div><div className="dfTxList">{transactions.map((x,i)=><div key={i}><b>{x.date||"-"} · {x.dong||""} {x.jibun||""}</b><strong>{money(x.amount)}</strong><span>{x.jimok||"지목 미표시"} · {fmt(x.area)}㎡ · 평당 {money(x.pricePerPyeong)}</span></div>)}</div></>:<div className="dfLandEmpty">{tx?.notice||"최근 12개월 비교 가능한 공식 토지 실거래가 없습니다."}</div>}<p className="dfLandSource">{tx?.source||"국토교통부 토지 매매 실거래가 자료"} · 취소거래 제외</p></section>
 <section className="dfLandAnalysisCard"><div className="dfLandCardHead"><div><small>05 · REGULATION</small><h2>토지·규제 분석</h2></div><span className={reg?.ok?"ok":"warn"}>{reg?.ok?"공식원천":"확인 필요"}</span></div><div className="dfLandMetrics"><div><span>용도지역</span><b>{zones.join(", ")||"확인 필요"}</b></div><div><span>용도지구</span><b>{districts.join(", ")||"해당 정보 없음"}</b></div><div><span>용도구역</span><b>{areas.join(", ")||"해당 정보 없음"}</b></div><div><span>도로접면</span><b>{reg?.characteristics?.roadFrontage||"확인 필요"}</b></div><div><span>건폐율</span><b>{confirmed?fmt(decision.buildingCoverageRatioPct)+"%":"추가 확인"}</b></div><div><span>용적률</span><b>{confirmed?fmt(decision.floorAreaRatioPct)+"%":"추가 확인"}</b></div></div>{(env?.regulation?.overlays||[]).length>0&&<div className="dfLandWarn"><b>중첩규제 확인</b><span>{env.regulation.overlays.map(x=>x.name).join(" · ")}</span></div>}<div className="dfRoadStatus"><b>접도 검토</b><span>{road?.cadastralAccess?.status==="boundary-shared"?"지목 도(도로) 필지와 지적경계 공유 확인":"지적경계 기준 추가 확인 필요"}</span><small>건축법상 법정도로 여부는 관할기관 확인 필요</small></div></section>
 <section className="dfLandAnalysisCard"><div className="dfLandCardHead"><div><small>06 · BUILDABILITY</small><h2>무엇을 얼마나 지을 수 있을까?</h2></div><span className={confirmed?"ok":"warn"}>{confirmed?"기본검토 가능":"추가확인 필요"}</span></div>{confirmed?<div className="dfLandMetrics"><div><span>대지면적</span><b>{fmt(env.parcel?.areaSqm)}㎡</b><em>약 {fmt(env.parcel?.areaPyeong)}평</em></div><div><span>최대 건축면적</span><b>{fmt(scale.maxBuildingAreaSqm)}㎡</b><em>약 {fmt(scale.maxBuildingAreaPyeong)}평</em></div><div className="wide"><span>용적률 산정 연면적</span><b>{fmt(scale.maxFarFloorAreaSqm)}㎡</b><em>약 {fmt(scale.maxFarFloorAreaPyeong)}평</em></div></div>:<div className="dfLandWarn"><b>자동계산을 보류했습니다.</b><span>{(decision.blockers||[]).map(x=>x.reason).filter(Boolean).join(" · ")||"용도지역·중첩규제·도로 등 적용조건을 추가 확인해야 합니다."}</span></div>}<p className="dfLandSource">{scale.note||"법정 최대 규모는 실제 설계 가능 규모와 다릅니다."}</p></section>
 <section className="dfLandAnalysisCard dfLandFinalCard"><div className="dfLandCardHead"><div><small>07 · AI CONCEPT</small><h2>AI 활용안 & 가설계</h2></div><span className={confirmed?"ok":"warn"}>{confirmed?"입력자료 준비":"법규확인 우선"}</span></div>{confirmed?<div className="dfAiLandReady"><b>가설계 입력값이 준비됐습니다.</b><span>대지 {fmt(env.parcel?.areaPyeong)}평 · 건폐율 {fmt(decision.buildingCoverageRatioPct)}% · 용적률 {fmt(decision.floorAreaRatioPct)}% · 용적률 산정 연면적 약 {fmt(scale.maxFarFloorAreaPyeong)}평</span><p>AI는 활용안을 제안할 수 있지만 건축 가능 용도·높이·주차·지구단위계획·개별법 조건 확인 전에는 인허가 가능안으로 표시하지 않습니다.</p></div>:<div className="dfLandEmpty">규제와 건축규모가 확인되면 AI 활용안·가설계 단계로 이어집니다.</div>}</section>
 </>}
 <section className="dfLandActionBox">{existing?<><b>이미 관심부동산에 등록되어 있습니다.</b><a className="adminPrimary" href={"/asset/"+existing.id}>내 부동산 상세보기 →</a></>:<><b>이 부동산의 변화를 계속 추적할까요?</b><button className="adminPrimary" disabled={busy||!address} onClick={save}>{busy?"저장 중…":"관심부동산 등록"}</button></>}{msg&&<span>{msg}</span>}</section>
 <section className="focusBlock"><div className="focusTitle"><div><small className="focusEyebrow">REGIONAL SIGNAL</small><h2>{region||"선택지역"} 개발뉴스</h2></div></div>{news.length?news.map(x=><a className="focusNews" href={"/focus/article?id="+x.id} key={x.id}><div><small>{x.category} · {region}</small><h3>{x.title}</h3><p>{new Date(x.published_at).toLocaleDateString("ko-KR")}</p></div><span className="newsArrow">→</span></a>):<div className="focusEmpty"><b>연결된 검증기사가 아직 없습니다.</b></div>}</section>
 <DFLiveAd placement="land" region={region||null}/><a className="dfLandBackAction" href="/search">다른 부동산 선택하기 →</a><DFBottomNav active="land"/></main>
}
