"use client";
import{useEffect,useState}from"react";
import{dfSupabase}from"../../../lib/df-browser";
import{DFSubHeader,DFBottomNav,DFToast,DFConfirmModal}from"../../../components/df-shell";
export default function Recent(){
 const[items,setItems]=useState([]),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[clearConfirm,setClearConfirm]=useState(false);
 async function load(){setLoading(true);const{data:{user}}=await dfSupabase.auth.getUser();if(!user){location.replace("/login?next=/my/recent");return}const{data,error}=await dfSupabase.from("df_recent_articles").select("article_id,last_viewed_at,view_count,df_articles(id,title,category,region_code,status)").eq("profile_id",user.id).order("last_viewed_at",{ascending:false}).limit(50);if(error)setMsg("최근 본 기사 기록을 불러오지 못했습니다.");else{setMsg("");setItems((data||[]).filter(x=>["published","corrected"].includes(x.df_articles?.status)))}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function clearAll(){if(busy)return;setBusy(true);const{data:{user}}=await dfSupabase.auth.getUser();if(!user){setBusy(false);return}const{error}=await dfSupabase.from("df_recent_articles").delete().eq("profile_id",user.id);if(error)setMsg("기록 삭제에 실패했습니다.");else await load();setBusy(false)}
 return <main className="focusShell dfHigh"><DFSubHeader title="최근 본 기사" kicker="HISTORY" back="/my" right={null}/><section className="focusBlock"><div className="focusTitle"><div><small className="focusEyebrow">HISTORY</small><h2>열람 기록</h2></div>{!loading&&items.length>0&&<button className="miniBtn" disabled={busy} onClick={()=>setClearConfirm(true)}>{busy?"삭제 중…":"전체삭제"}</button>}</div>{loading?<div className="focusEmpty"><b>열람 기록을 불러오는 중입니다.</b></div>:items.length?items.map(x=>{const a=x.df_articles;return <a className="focusNews" href={"/focus/article?id="+x.article_id} key={x.article_id}><div><small>{a.category}{a.region_code?" · "+a.region_code:""}</small><h3>{a.title}</h3><p>{new Date(x.last_viewed_at).toLocaleString("ko-KR")}</p></div><span className="newsArrow">→</span></a>}):<div className="focusEmpty"><b>최근 본 기사가 없습니다.</b><span>로그인 상태에서 읽은 기사가 자동으로 기록됩니다.</span></div>}</section><DFToast message={msg} onClose={()=>setMsg("")}/><DFConfirmModal open={clearConfirm} title="최근 본 기사 전체삭제" body="열람 기록을 모두 삭제합니다. 이 작업은 되돌릴 수 없습니다." confirmLabel="전체삭제" danger onCancel={()=>setClearConfirm(false)} onConfirm={()=>{setClearConfirm(false);clearAll()}}/><DFBottomNav active="my"/></main>
}
