"use client";
import{useEffect,useState}from"react";
import{dfSupabase}from"../../../lib/df-browser";
import{DFSubHeader,DFBottomNav,DFToast,DFConfirmModal}from"../../../components/df-shell";
export default function Properties(){
 const[items,setItems]=useState([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[loading,setLoading]=useState(true),[removeId,setRemoveId]=useState("");
 async function load(){setLoading(true);const{data:{user}}=await dfSupabase.auth.getUser();if(!user){location.replace("/login?next=/my/properties");return}const{data,error}=await dfSupabase.from("df_land_watchlists").select("*").eq("profile_id",user.id).order("created_at",{ascending:false});if(error)setMsg("관심부동산을 불러오지 못했습니다.");else{setMsg("");setItems(data||[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function toggle(x){if(busy)return;setBusy(x.id);const{error}=await dfSupabase.from("df_land_watchlists").update({is_active:!x.is_active}).eq("id",x.id);if(error)setMsg("추적 상태 변경에 실패했습니다.");else await load();setBusy("")}
 async function remove(id){if(busy)return;setBusy(id);const{error}=await dfSupabase.from("df_land_watchlists").delete().eq("id",id);if(error)setMsg("관심부동산 삭제에 실패했습니다.");else await load();setBusy("")}
 return <main className="focusShell dfHigh"><DFSubHeader title="관심부동산" kicker="MY PROPERTY" back="/my" right={null}/><section className="focusBlock"><div className="focusTitle"><div><small className="focusEyebrow">DDANGJIPGO</small><h2>등록한 부동산</h2></div><a href="/search">+ 등록</a></div>{loading?<div className="focusEmpty"><b>관심부동산을 불러오는 중입니다.</b></div>:items.length?<div className="dfPropertyList">{items.map(x=><article key={x.id}><a href={"/asset/"+x.id}><small>{x.region_code||"지역 미분류"} · {x.is_active?"추적중":"중지"}</small><b>{x.label||x.address_text||"관심부동산"}</b><span>{x.address_text}</span></a><div className="dfListActions"><button disabled={busy===x.id} onClick={()=>toggle(x)}>{busy===x.id?"처리 중":x.is_active?"일시중지":"추적시작"}</button><button disabled={busy===x.id} onClick={()=>setRemoveId(x.id)}>삭제</button></div></article>)}</div>:<div className="focusEmpty"><b>등록한 부동산이 없습니다.</b><span>주소를 선택해 관심부동산으로 저장하면 관련 뉴스와 알림을 연결합니다.</span><a href="/search">땅짚고에서 등록하기 →</a></div>}</section><DFToast message={msg} onClose={()=>setMsg("")}/><DFConfirmModal open={!!removeId} title="관심부동산 삭제" body="삭제하면 이 부동산의 추적과 연결정보를 더 이상 볼 수 없습니다." confirmLabel="삭제" danger onCancel={()=>setRemoveId("")} onConfirm={()=>{const id=removeId;setRemoveId("");remove(id)}}/><DFBottomNav active="my"/></main>
}
